### ISSUE TITLE
Cross-domain image adaptation

### ISSUE THREAD

**Issue by backpass** [cassiePython/cddfm3d#1]
Hi, thank you for your work! 

I like your approach with fixing the same style space for different domains and would have liked to reproduce it. So I want to be sure about what exactly was your approach.
```
To keep the latent consistency across all generators, we freeze the network layers relevant to latent embedding. To be specific, since we use the style space 𝒮, all style convolution layers and tRGB layers, Menglei: i.e., the affine transformation layers, are fixed during the finetuning.
````
Hence, all the [affine](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/networks.py#L278) layers are freezed together with all [tRGB](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/networks.py#L371) layers?

```
 Besides that, we use exactly the same loss functions and hyper-parameters as in StyleGAN2
```
Would it affect the result if stylegan-ada is used for finetuning a new model?

Looking forward to hearing from you!

**Comment by cassiePython** [comment]
> Hi, thank you for your work!
> 
> I like your approach with fixing the same style space for different domains and would have liked to reproduce it. So I want to be sure about what exactly was your approach.
> 
> ```
> To keep the latent consistency across all generators, we freeze the network layers relevant to latent embedding. To be specific, since we use the style space 𝒮, all style convolution layers and tRGB layers, Menglei: i.e., the affine transformation layers, are fixed during the finetuning.
> ```
> 
> Hence, all the [affine](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/networks.py#L278) layers are freezed together with all [tRGB](https://github.com/NVlabs/stylegan2-ada-pytorch/blob/main/training/networks.py#L371) layers?
> 
> ```
>  Besides that, we use exactly the same loss functions and hyper-parameters as in StyleGAN2
> ```
> 
> Would it affect the result if stylegan-ada is used for finetuning a new model?
> 
> Looking forward to hearing from you!

1. For fixed layers: You are right. If you want to reproduce the results, please adopt the training technique of FreezeG (https://github.com/bryandlee/FreezeG/blob/master/stylegan2/train.py). These layers are fixed during updating the discriminator.  
2. For StyleGAN-Ada: I haven't tried StyleGAN-Ada, but I think it can replace StyleGAN2 in our work and I recommend to use it for Data Preparation(Step 0) to make the latent space consistency. 

Thanks.

**Comment by backpass** [comment]
@cassiePython Thank you for your answer!

1. I haven't run into this approach yet, do you mean freezing only specific layers for discriminator update as in this [line](https://github.com/bryandlee/FreezeG/blob/40d2580b9082737331cefe7fe4dded120f457c5c/stylegan2/train.py#L176)? Which [layers](https://github.com/bryandlee/FreezeG/blob/master/stylegan2/train.py#L384) have you frozen?
2. What do you mean by Data Preparation?

Thanks in advance.

**Comment by cassiePython** [comment]
@backpass  

1. Yes. Freezing the layers that transfer W+ Space to StyleSpace (You can find these layers through reading code in 'stylegan2-pytorch/model.py' ) while updating the discriminator. 
2. Please refer to '1. Data Preparation' in Readme.

**Comment by backpass** [comment]
Thank you!
