### ISSUE TITLE
code for Attribute-Adaptive Layer Selection Algorithm

### ISSUE THREAD

**Issue by Seeyn** [cassiePython/cddfm3d#4]
Hi! Thanks for your great work. It seems that there is no code for the algorithm "Attribute-Adaptive Layer Selection Algorithm"  mentioned in your paper.

**Comment by Seeyn** [comment]
![image](https://user-images.githubusercontent.com/48508432/172041139-b1ac7ac7-13b9-4b06-9ea8-c0431e3b16b4.png)

**Comment by cassiePython** [comment]
I already provided the layer selection results in the "network.py". For a specific attribute, unrelated layers are not modified. Please check forward functions in RigNetEncoder. 


> Hi! Thanks for your great work. It seems that there is no code for the algorithm "Attribute-Adaptive Layer Selection Algorithm" mentioned in your paper.

**Comment by Seeyn** [comment]
Thanks for your prompt reply.  I check the forward functions in RigNetEncoder.
![image](https://user-images.githubusercontent.com/48508432/172185103-d3368f9d-a5ac-463e-be28-785d96a8fb2c.png)

However, as the figure shows, it does feed all style codes from each layer(26 in total) into the RigNetEncoder.

**Comment by cassiePython** [comment]
Sorry. It is in RigNetDecoder, not RigNetEncoder. 

> Thanks for your prompt reply. I check the forward functions in RigNetEncoder. ![image](https://user-images.githubusercontent.com/48508432/172185103-d3368f9d-a5ac-463e-be28-785d96a8fb2c.png)
> 
> However, as the figure shows, it does feed all style codes from each layer(26 in total) into the RigNetEncoder.

**Comment by Seeyn** [comment]
Thanks! I check the RigNetDecoder and find out that only part of the output from the encoder is fed to the decoder.
![image](https://user-images.githubusercontent.com/48508432/172189731-e642694e-bab7-4f78-be4d-ddd076b3e4b5.png)

![image](https://user-images.githubusercontent.com/48508432/172187534-fc5672d2-7009-461f-a51b-4c0b402881c2.png)
But it is inconsistent with the design shown in your paper since the target of the selection algorithm is the style codes instead of the output from the encoder.

**Comment by cassiePython** [comment]
@Seeyn  Thanks. The target of the layer selection algorithm is certainly the style code. This is consistent with our Algorithm 1. But after thinking twice, I think you are right that the figure is easy to be misunderstood. 

Modify only selected layers: 

<img width="698" alt="image" src="https://user-images.githubusercontent.com/15982113/172198644-b1f4ef04-0dd5-4b6b-a633-05337c222f34.png">

**Comment by Seeyn** [comment]
Thank you for your patient and kind explanation
