### ISSUE TITLE
Error when run evaluate.py

### ISSUE THREAD

**Issue by zhanghm1995** [cassiePython/cddfm3d#5]
Hi, firstly thank you for sharing this work.

When I run the `python evaluate.py --name apnet_wpdc --model APModel` command in **Attribute Prediction** part, I got the error as follows:
```bash
Model APModel was created
  0%|                                                                                                                                                                                     | 0/199 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "evaluate.py", line 192, in <module>
    model.test_shape()
  File "evaluate.py", line 159, in test_shape
    latent_pred, params_source, params_pred = self._model.forward_test(latent, pca_id, pca_val)
TypeError: forward_test() takes 2 positional arguments but 4 were given
```
And when I check the code, I found the function of `forward_test` in **APModel** class exactly accept only one `latent` argument, however, the above function need three arguments.

I don't know how to fix this error.

**Comment by cassiePython** [comment]
@zhanghm1995 You can change it to 'model.test()' to evaluate the APModel.

**Comment by zhanghm1995** [comment]
@cassiePython I also change it to `model.test()`, but I got the results like these:
![image](https://user-images.githubusercontent.com/24753281/174304503-efb6ab32-05b0-42eb-8b8d-63a7359c9865.png)

The rendered 3DMM face all are front-faced, and the mouth keep the same. While in your README, the visualization is not like mine.

BTW, I train the APModel by using 4k images.

**Comment by cassiePython** [comment]
@zhanghm1995 Please refer to this [issue](https://github.com/cassiePython/cddfm3d/issues/3) .
